<a href="https://colab.research.google.com/github/MariiaSam/DS_homeWork/blob/main/Hw4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [142]:
# 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [141]:
# 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
matrix = np.zeros((3, 3), dtype=int)

print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [96]:
# 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення
matrix = np.random.randint(1, 11, size=(5,5))

print(matrix)

[[ 7  7  3  8  6]
 [ 8  1  9 10  3]
 [10  8 10  7  2]
 [ 4 10  3  5  4]
 [ 9  3  1  3  5]]


In [130]:
# 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення
matrix = np.random.rand(4,4)

print(matrix)

[[0.69370646 0.35834635 0.98141805 0.34242676]
 [0.34988446 0.56652309 0.31709539 0.2036209 ]
 [0.51473686 0.29053558 0.69696028 0.54437074]
 [0.7763211  0.86629614 0.17254451 0.25602648]]


In [129]:
# 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення
a = np.random.randint(1, 11, size=(5), dtype=int)
b = np.random.randint(1, 11, size=(5), dtype=int)

print(a+b)
print(a-b)
print(a*b)


[20  5  5 13  2]
[ 0  1  1 -1  0]
[100   6   6  42   1]


In [99]:
# 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток
vector1 = np.array([1, 2, 3, 4, 5, 6, 7])
vector2 = np.array([2, 4, 6, 1, 3, 5, 9])

print(np.dot(vector1, vector2))

140


In [131]:
# 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою
matrix1 = np.random.randint(1, 11, size=(2,2), dtype=int)
matrix2 = np.random.randint(1, 11, size=(2,3), dtype=int)

print(np.dot(matrix1, matrix2))

[[ 47  52  35]
 [ 98 106  75]]


In [101]:
# 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
matrix = np.random.randint(1, 11, size=(3,3), dtype=int)
matrix_inv = np.linalg.inv(matrix)
print(matrix_inv)


[[ 0.23595506 -0.19101124  0.03370787]
 [-0.73033708  1.06741573 -0.24719101]
 [ 0.1011236  -0.2247191   0.15730337]]


In [102]:
# 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її
matrix = np.random.rand(4, 4)
print(matrix.T)

[[2.11968264e-01 6.94728199e-01 8.15129307e-01 3.10238894e-01]
 [3.19161738e-01 2.72297914e-01 6.83092244e-01 6.82573698e-01]
 [5.46787957e-01 4.99807976e-01 5.79183851e-04 1.21743007e-01]
 [2.91240187e-01 2.71385885e-01 1.93363514e-01 9.72108284e-01]]


In [133]:
# 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор
matrix = np.random.randint(1, 11, size=(3,4), dtype=int)
vector = np.random.randint(1, 11, size=(4), dtype=int)

print(np.dot(matrix, vector))

[ 48 139 160]


In [134]:
# 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор
matrix = np.random.rand(2, 3)
vector = np.random.rand(3)

print(np.dot(matrix, vector))

[0.2749688  0.46662123]


In [105]:
# 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення
matrix1 = np.random.randint(1, 11, size=(2,2), dtype=int)
matrix2 = np.random.randint(1, 11, size=(2,2), dtype=int)

print(matrix1*matrix2)

[[ 3 21]
 [24 18]]


In [135]:
# 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток
matrix1 = np.random.randint(1, 11, size=(2,2), dtype=int)
matrix2 = np.random.randint(1, 11, size=(2,2), dtype=int)

print(np.dot(matrix1, matrix2))


[[ 63  25]
 [108  56]]


In [110]:
# 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці
matrix = np.random.randint(1, 101, size=(5,5), dtype=int)
print(matrix)

print(matrix.sum())

[[ 22  58  87  67  27]
 [ 78  92  15  28  94]
 [ 58  45  94  99  79]
 [ 29  86  91  70  89]
 [ 11  90  38 100  77]]
1624


In [136]:
# 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю
matrix1 = np.random.randint(1, 11, size=(4,4), dtype=int)
matrix2 = np.random.randint(1, 11, size=(4,4), dtype=int)

print(matrix1 - matrix2)

[[-1  1 -3  6]
 [ 2 -8 -1 -2]
 [-7  0 -2 -1]
 [-7  2 -4  2]]


In [145]:
# 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
matrix = np.random.rand(3, 3)
row_sums = matrix.sum(axis=1).reshape(-1, 1)

print(row_sums)

[[2.38920578]
 [0.88784073]
 [2.54449427]]


In [139]:
# 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
matrix = np.random.randint(0, 11, (3, 4))
print(matrix)

matrix2 = matrix ** 2

# matrix2 = matrix ** matrix

print(matrix2)

[[10 10 10  6]
 [ 3  4  2 10]
 [10 10  3  4]]
[[100 100 100  36]
 [  9  16   4 100]
 [100 100   9  16]]


In [140]:
# 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел
vector1 = np.random.randint(1, 51, size=4)
print(vector1)

vector2 = np.sqrt(vector1)
print(vector2)


[ 8 33 14 32]
[2.82842712 5.74456265 3.74165739 5.65685425]


**Завдання 2 (додаткове, за бажанням) **


In [3]:
# 1. Замініть усі непарні числа в arr на -1 arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 !=0] = -1

print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [14]:
# 2. Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)

arr2 = arr.reshape(2, -1)
print(arr2)


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [8]:
# 3. Створіть два двовимірні масиви а і b, та складіть масиви їх вертикально

a = np.random.randint(0, 11, (3, 3))
b = np.random.randint(0, 11, (3, 3))
print(a)
print(b)

c = np.vstack((a, b))
print(c)



[[9 8 8]
 [5 0 4]
 [5 9 3]]
[[ 6  9  6]
 [ 5 10  2]
 [ 6  0  6]]
[[ 9  8  8]
 [ 5  0  4]
 [ 5  9  3]
 [ 6  9  6]
 [ 5 10  2]
 [ 6  0  6]]


In [14]:
# 4. Створіть наступний шаблон без жорсткого кодування(Hard coding) . Використовуйте лише функції Numpy і наведений нижче масив введення Input:a = np.array([1,2,3]) Output:array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

a = np.array([1,2,3])

a_repeated = np.repeat(a, 3)
print(a_repeated)

a_tiled = np.tile(a, 3)
print(a_tiled)

a_output = np.concatenate((a_repeated, a_tiled))
print(a_output)


[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [3]:
# 5. Отримайте спільні елементи між a і b

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c = np.intersect1d(a, b)
print(c)



[2 4]


In [10]:
# 6. Отримайте позиції(індекси) перших 5 максимальних значень у заданому масиві a
np.random.seed(100) # коли цей код буде виконаний, ми отримаємо один і той самий набір випадкових чисел
a = np.random.uniform(1,50, 20)
print(a)

b = np.argsort(a)[-5:][::-1]
print(b)



[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
[15 10  3  7 18]


In [12]:
# 7. Вилучіть усі значення NaN із одновимірного масиву

а=np.array([1,2,3,np.nan,5,6,7,np.nan])

b = a[~np.isnan(a)]
print(b)

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]


In [13]:
# 8. Обчисліть евклідову відстань між двома масивами a і b.

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

dist = np.linalg.norm(a-b)
print(dist)

6.708203932499369


In [17]:
# 9. Знайдіть індекс 5-го повторення числа 1 у масиві x

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

x_index = np.where(x == 1)[0][4]
print(x_index)



8


In [ ]:
# 10. Знайдіть повторювані записи (від 2-го випадку повторення і далі) у заданому масиві і позначте їх як True. Перше повторення має бути False.

# Input np.random.seed(100) a = np.random.randint(0, 5, 10)

[0 0 3 0 2 4 2 2 2 2] #Output [False True False True False False True True True True]

